#ifndef PROGRAMA_VARIAVEIS_GLOBAIS_H
#define PROGRAMA_VARIAVEIS_GLOBAIS_H

#define MAX_AGENTES_IMOBILIARIOS 15
#define  MAX_ADMINISTRADORES 100
#define  MAX_CLIENTES 200
#define HORA_INICIO_AGENTE_IMOBILIARIO (9 * 60)
#define HORA_FIM_AGENTE_IMOBILIARIO (19 * 60)


# define SUM_AGENTES_IMOBILIARIOS 120 ////(15+14-13+(...)+3+2+1)

#endif //PROGRAMA_VARIAVEIS_GLOBAIS_H
